.PHONY: all clean

KSC:=ksc

KSYS_DIR:=kaitai
PYS_DIR:=fcdstools/kaitai

KSYS:=\
    $(KSYS_DIR)/fds_file_header_block.ksy \
    $(KSYS_DIR)/fds_header.ksy \
    $(KSYS_DIR)/fds_info_block.ksy
PYS:=$(patsubst %.ksy,$(PYS_DIR)/%.py,$(notdir $(KSYS)))

TARGET:=$(PYS)

$(PYS_DIR)/%.py: $(KSYS_DIR)/%.ksy
	ksc --target python \
	    --python-package '.' \
	    --outdir $(PYS_DIR) \
	    --verbose file \
	    $<

all: $(TARGET)

clean:
	-$(RM) $(TARGET)
